### ISSUE TITLE
change language?

### ISSUE THREAD

**Issue by d1qqn** [hoangminh5210119/deauther#2]
how can i change the language of the captive portals?

or can you please upload a english version?

**Comment by hoangminh5210119** [comment]
I have uploaded an English version.

**Comment by d1qqn** [comment]
hi,

only facebook is in english, can you please change the others to english, too?

and can you please show me the http? code from the sites,
and explain how to create a hexadecimal code from the webfiles,
which can be packed into the webfiles.h file?

i would like to understand the technology behind it and try to create more phishing sites

thankz
